name: Deploy Rating API to ACR and Kubernetes
on:
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master
  workflow_dispatch:

permissions: 
  id-token: write 
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/ratings-api:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Set up kubeconfig
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      # Option 1: Skip secret creation entirely since it exists
      - name: Deploy to Kubernetes
        run: |
          # Replace the image tag in the deployment file
          sed -i "s|<acr_name>.azurecr.io/ratings-api:v1|${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/ratings-api:${{ github.sha }}|g" ratingapi-acr-to-k8s.yaml
          
          # Apply the deployment
          kubectl apply -f ratingapi-acr-to-k8s.yaml

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/ratings-api
          kubectl get services -o wide